In [1]:
import urllib.request
import zipfile
import os
from pathlib import Path

url = "https://archive.ics.uci.edu/static/public/228/sms+spam+collection.zip"
zip_path= "sms_spam_collection.zip"
extracted_path= "sms_spam_collection"
data_file_path= Path(extracted_path)  / "SMSSpamCollection.tsv"

def download_and_unzip_spam_data(
        url, zip_path, extracted_path, data_file_path):
    if data_file_path.exists():  
        print(f"{data_file_path} already exists. Skipping download"
              "and extraction."
              )
        return

    
    with urllib.request.urlopen(url) as response:
        with open(zip_path, "wb" ) as out_file:
            out_file.write(response.read())

    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extracted_path)

    original_file_path= Path(extracted_path)/ "SMSSpamCollection"
    os.rename(original_file_path, data_file_path)
    print(f"file donwloaded and saved as {data_file_path}")

download_and_unzip_spam_data(url, zip_path, extracted_path, data_file_path)

sms_spam_collection\SMSSpamCollection.tsv already exists. Skipping downloadand extraction.

In [2]:
import pandas as pd
df= pd.read_csv(
    data_file_path, sep= "\t", header= None, names= ["Label", "Text"]
)
df

     Label                                               Text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
print(df["Label"].value_counts())

Label
ham     4825
spam     747
Name: count, dtype: int64

In [4]:

print( df[df["Label"]== "spam"]  )

     Label                                               Text
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...
11    spam  SIX chances to win CASH! From 100 to 20,000 po...
...    ...                                                ...
5537  spam  Want explicit SEX in 30 secs? Ring 02073162414...
5540  spam  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547  spam  Had your contract mobile 11 Mnths? Latest Moto...
5566  spam  REMINDER FROM O2: To get 2.50 pounds free call...
5567  spam  This is the 2nd time we have tried 2 contact u...

[747 rows x 2 columns]

In [5]:
def create_balanced_dataset(df):
    num_spam= df[df["Label"]== "spam"].shape[0]
    ham_subset= df[df["Label"]== "ham"].sample(
        num_spam, random_state=123
    )

    balanced_df = pd.concat([
        ham_subset, df[df["Label"]== "spam"]
    ])
    return balanced_df

balanced_df= create_balanced_dataset(df)
print(balanced_df["Label"].value_counts())

Label
ham     747
spam    747
Name: count, dtype: int64

In [6]:
balanced_df["Label"]= balanced_df["Label"].map({"ham":0, "spam":1})

In [7]:
def random_split(df, train_frac, validation_frac):

    df= df.sample(
        frac=1, random_state= 123
    ).reset_index(drop = True)
    train_end = int(len(df) * train_frac)
    validation_end = train_end + int(len(df) * validation_frac)

    train_df = df[: train_end]
    validation_df= df[train_end: validation_end]

    test_df= df[validation_end:]

    return train_df, validation_df, test_df

train_df, validation_df, test_df= random_split(
    balanced_df, 0.7, 0.1
)

In [8]:
train_df.to_csv("train.csv", index= None)
validation_df.to_csv("validation.csv", index= None)
test_df.to_csv("test.csv", index= None)

In [9]:
import tiktoken
tokenizer= tiktoken.get_encoding("gpt2")
print(tokenizer.encode("<|endoftext|>", allowed_special= {"<|endoftext|>"}))

[50256]

In [10]:
print(tokenizer.decode([50256]))

<|endoftext|>

In [11]:
print(tokenizer.decode([91, 437, 1659, 5239, 91]))

|endoftext|

dataset class

In [12]:
import torch
import pandas as pd
from torch.utils.data import Dataset


class SpamDataset(Dataset):
    def __init__(self, csv_file, tokenizer, max_length=None, pad_token_id=50256):
        self.data = pd.read_csv(csv_file)

        # 1. Encode all texts
        self.encoded_texts = [
            tokenizer.encode(text)
            for text in self.data["Text"]
        ]

        # Determine maximum sequence length
        if max_length is None:
            self.max_length = self.longest_encoded_length()
        else:
            self.max_length = max_length

        # 2. Truncate sequences
        self.encoded_texts = [
            encoded_text[:self.max_length]
            for encoded_text in self.encoded_texts
        ]

        # 3. Pad sequences
        self.encoded_texts = [
            encoded_text + [pad_token_id] * (self.max_length - len(encoded_text))
            for encoded_text in self.encoded_texts
        ]

    def __getitem__(self, index):
        encoded = self.encoded_texts[index]
        label = self.data.iloc[index]["Label"]

        return (
            torch.tensor(encoded, dtype=torch.long),
            torch.tensor(label, dtype=torch.long),
        )

    def __len__(self):
        return len(self.data)

    def longest_encoded_length(self):
        max_length = 0

        for encoded_text in self.encoded_texts:
            encoded_length = len(encoded_text)
            if encoded_length > max_length:
                max_length = encoded_length

        return max_length

In [13]:
data= pd.read_csv("train.csv")
data

      Label                                               Text
0         0                Dude how do you like the buff wind.
1         0  Tessy..pls do me a favor. Pls convey my birthd...
2         1  Reminder: You have not downloaded the content ...
3         1  Got what it takes 2 take part in the WRC Rally...
4         1  Shop till u Drop, IS IT YOU, either 10K, 5K, £...
...     ...                                                ...
1040      1  4mths half price Orange line rental & latest c...
1041      1  Thanks for the Vote. Now sing along with the s...
1042      1  IMPORTANT INFORMATION 4 ORANGE USER 0796XXXXXX...
1043      1  Urgent! call 09066612661 from landline. Your c...
1044      0  His frens go then he in lor. Not alone wif my ...

[1045 rows x 2 columns]

In [14]:
for i, text in enumerate(data["Text"]):
    print(i, text , "\n")

    if(i>10):
        break

0 Dude how do you like the buff wind.

1 Tessy..pls do me a favor. Pls convey my birthday wishes to Nimya..pls dnt forget it. Today is her birthday Shijas

2 Reminder: You have not downloaded the content you have already paid for. Goto http://doit. mymoby. tv/ to collect your content.

3 Got what it takes 2 take part in the WRC Rally in Oz? U can with Lucozade Energy! Text RALLY LE to 61200 (25p), see packs or lucozade.co.uk/wrc & itcould be u!

4 Shop till u Drop, IS IT YOU, either 10K, 5K, £500 Cash or £100 Travel voucher, Call now, 09064011000. NTT PO Box CR01327BT fixedline Cost 150ppm mobile vary

5 Am on a train back from northampton so i'm afraid not! I'm staying skyving off today ho ho! Will be around wednesday though. Do you fancy the comedy club this week by the way?

6 Dude. What's up. How Teresa. Hope you have been okay. When i didnt hear from these people, i called them and they had received the package since dec  &lt;#&gt; . Just thot you'ld like to know. Do have a fantastic year and all the best with your reading. Plus if you can really really Bam first aid for Usmle, then your work is done.

7 Hi, the SEXYCHAT girls are waiting for you to text them. Text now for a great night chatting. send STOP to stop this service

8 I've got  &lt;#&gt; , any way I could pick up?

9 Quite late lar... Ard 12 anyway i wun b drivin...

10 I'm good. Have you registered to vote?

11 Beautiful truth : Expression of the face could Be seen by everyone... But the depression of heart Could be understood only By the Loved ones.. Gud Ni8;-)

In [15]:
train_dataset= SpamDataset(
    csv_file= "train.csv",
    max_length= None,
    tokenizer= tokenizer
)

In [16]:
print(train_dataset.max_length )

120

In [17]:
val_dataset= SpamDataset(
    csv_file = "validation.csv",
    max_length = train_dataset.max_length,
    tokenizer= tokenizer
)

test_dataset = SpamDataset(
    csv_file= "test.csv",
    max_length= train_dataset.max_length,
    tokenizer= tokenizer
)

In [18]:
# dataloader
import torch
from torch.utils.data import DataLoader
num_workers=0
batch_size= 8
torch.manual_seed(123)

train_loader = DataLoader(
    dataset= train_dataset,
    batch_size= batch_size,
    shuffle = True,
    num_workers= num_workers,
    drop_last= True
)

val_loader= DataLoader(
    dataset= val_dataset,
    batch_size= batch_size,
    num_workers= num_workers,
    drop_last= False
)

test_loader= DataLoader(
    dataset= test_dataset,
    batch_size= batch_size,
    num_workers= num_workers,
    drop_last= False  
)

In [19]:
for input_batch, target_batch in train_loader:
    pass
print("input batch dimensions :", input_batch.shape)
print("label batch dimensions :", target_batch.shape)

input batch dimensions : torch.Size([8, 120])
label batch dimensions : torch.Size([8])

In [20]:
print(f"{len(train_loader)} training batches")
print(f"{len(val_loader)} validation batches")

130 training batches
19 validation batches

In [21]:
CHOOSE_MODEL = "gpt2-small (124M)"
INPUT_PROMPT = "Every effort moves"

BASE_CONFIG = {
    "vocab_size": 50257,      #1
    "context_length": 1024,   #2
    "drop_rate": 0.0,         #3
    "qkv_bias": True          #4
}

model_configs = {
    "gpt2-small (124M)": {
        "emb_dim": 768,
        "n_layers": 12,
        "n_heads": 12
    },
    "gpt2-medium (355M)": {
        "emb_dim": 1024,
        "n_layers": 24,
        "n_heads": 16
    },
    "gpt2-large (774M)": {
        "emb_dim": 1280,
        "n_layers": 36,
        "n_heads": 20
    },
    "gpt2-xl (1558M)": {
        "emb_dim": 1600,
        "n_layers": 48,
        "n_heads": 25
    },
}

BASE_CONFIG.update(model_configs[CHOOSE_MODEL])

In [23]:
from gpt_download import download_and_load_gpt2
from previous_chapters import GPTModel, load_weights_into_gpt

model_size= CHOOSE_MODEL.split(" ")[-1].strip("(").rstrip(")")
settings, params= download_and_load_gpt2(
    model_size= model_size, models_dir= "gpt2"
)

model= GPTModel(BASE_CONFIG)
load_weights_into_gpt(model, params)
model.eval()

File already exists and is up-to-date: gpt2\124M\checkpoint
File already exists and is up-to-date: gpt2\124M\encoder.json
File already exists and is up-to-date: gpt2\124M\hparams.json
File already exists and is up-to-date: gpt2\124M\model.ckpt.data-00000-of-00001
File already exists and is up-to-date: gpt2\124M\model.ckpt.index
File already exists and is up-to-date: gpt2\124M\model.ckpt.meta
File already exists and is up-to-date: gpt2\124M\vocab.bpe

GPTModel(
  (tok_emb): Embedding(50257, 768)
  (pos_emb): Embedding(1024, 768)
  (drop_emb): Dropout(p=0.0, inplace=False)
  (trf_blocks): Sequential(
    (0): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (1): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (2): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (3): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (4): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (5): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (6): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (7): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (8): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (9): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (10): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (11): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
  )
  (final_norm): LayerNorm()
  (out_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [30]:
from previous_chapters import generate_text_simple, text_to_token_ids, token_ids_to_text

text_1= "jai"
token_ids = generate_text_simple(
    model= model,
    idx= text_to_token_ids(text_1, tokenizer),
    max_new_tokens= 115,
    context_size= BASE_CONFIG["context_length"]
)

print(token_ids_to_text(token_ids, tokenizer))

jai, a former member of the U.S. Army's Special Operations Command, said the U.S. military has been "very clear" that it will not use force against the Islamic State.

"We are not going to use force against the Islamic State," he said. "We are not going to use force against the Islamic State. We are not going to use force against the Islamic State."

The U.S. military has been in the midst of a major campaign to defeat the Islamic State, which has taken over large parts of Iraq and

In [31]:
print(model)

GPTModel(
  (tok_emb): Embedding(50257, 768)
  (pos_emb): Embedding(1024, 768)
  (drop_emb): Dropout(p=0.0, inplace=False)
  (trf_blocks): Sequential(
    (0): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (1): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (2): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (3): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (4): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (5): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (6): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (7): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (8): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (9): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (10): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (11): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
  )
  (final_norm): LayerNorm()
  (out_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [32]:
for param in model.parameters():
    param.requires_grad= False

In [33]:
torch.manual_seed(123)
num_classes=2
model.out_head = torch.nn.Linear(
    in_features= BASE_CONFIG["emb_dim"],
    out_features= num_classes
)

In [34]:
for param in model.trf_blocks[-1].parameters():
    param.requires_grad= True
for param in model.final_norm.parameters():
    param.requires_grad= True

In [35]:
print(model)

GPTModel(
  (tok_emb): Embedding(50257, 768)
  (pos_emb): Embedding(1024, 768)
  (drop_emb): Dropout(p=0.0, inplace=False)
  (trf_blocks): Sequential(
    (0): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (1): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (2): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (3): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (4): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (5): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (6): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (7): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (8): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (9): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (10): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
    (11): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=True)
        (W_key): Linear(in_features=768, out_features=768, bias=True)
        (W_value): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNorm()
      (norm2): LayerNorm()
      (drop_resid): Dropout(p=0.0, inplace=False)
    )
  )
  (final_norm): LayerNorm()
  (out_head): Linear(in_features=768, out_features=2, bias=True)
)

In [37]:
inputs= tokenizer.encode("do you have time ??")
inputs= torch.tensor(inputs).unsqueeze(0)
print("inputs", inputs)
print("input dims", inputs.shape)

inputs tensor([[ 4598,   345,   423,   640, 19153]])
input dims torch.Size([1, 5])

In [41]:
with torch.no_grad():
    outputs= model(inputs)
print("outputs:\n", outputs)
print("op dims:" ,outputs.shape)

outputs:
 tensor([[[-1.5465,  0.9756],
         [-3.7792,  7.4043],
         [-2.3096,  6.4195],
         [-3.6631,  4.2262],
         [-4.0467,  4.9151]]])
op dims: torch.Size([1, 5, 2])

In [42]:
print("last output token:" , outputs[:, -1, :])

last output token: tensor([[-4.0467,  4.9151]])

In [54]:
def calc_accuracy_loader(data_loader, model, device, num_batches= None):
    model.eval()
    correct_predictions, num_examples= 0,0

    if num_batches is None:
        num_batches = len(data_loader)
    else :
        num_batches= min(num_batches, len(data_loader))

    for i , (input_batch, target_batch) in enumerate(data_loader):
        if i< num_batches:
            input_batch= input_batch.to(device)
            target_batch= target_batch.to(device)
            # print("hare" ,i, input_batch.shape, input_batch)
            with torch.no_grad():
                logits= model(input_batch)[:, -1, :]
                print("haribol", logits)
            predicted_labels = torch.argmax(logits, dim=-1)
            # print("krishna",i,predicted_labels.shape, predicted_labels)

            num_examples += predicted_labels.shape[0]
            correct_predictions +=(
                (predicted_labels == target_batch).sum().item()
            )
            # print("redhe",i, correct_predictions)
        else:
            break

    
    return correct_predictions / num_examples

In [55]:
device= torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

torch.manual_seed(123)
train_accuracy = calc_accuracy_loader(
    train_loader, model, device, num_batches=10
)

print(f"Training accuracy : {train_accuracy*100:.2f}%")

haribol tensor([[-2.3507,  2.6437],
        [-2.4689,  2.7582],
        [-2.3161,  2.7413],
        [-2.4349,  2.7347],
        [-2.3471,  2.7348],
        [-2.4429,  2.7201],
        [-2.4104,  2.8182],
        [-2.4334,  2.7510]])
haribol tensor([[-2.3874,  2.8109],
        [-2.4590,  2.7197],
        [-2.3133,  2.7725],
        [-2.4135,  2.6959],
        [-2.4366,  2.7930],
        [-2.4560,  2.7447],
        [-2.3810,  2.7074],
        [-2.4547,  2.7679]])
haribol tensor([[-2.4327,  2.8559],
        [-2.4020,  2.8596],
        [-2.4900,  2.7955],
        [-2.3863,  2.6997],
        [-2.3134,  2.7227],
        [-2.3506,  2.6729],
        [-2.4694,  2.7965],
        [-2.4771,  2.7097]])
haribol tensor([[-2.3716,  2.7096],
        [-2.5092,  2.8159],
        [-2.3230,  2.7485],
        [-2.4385,  2.7252],
        [-2.1310,  2.6975],
        [-2.3092,  2.7141],
        [-2.4015,  2.7743],
        [-2.3950,  2.6884]])
haribol tensor([[-2.2588,  2.6989],
        [-2.4250,  2.7171],
        [-2.4087,  2.7913],
        [-2.2884,  2.7166],
        [-2.5116,  2.7676],
        [-2.4221,  2.7186],
        [-2.3047,  2.7547],
        [-2.3318,  2.6881]])
haribol tensor([[-2.2939,  2.7409],
        [-2.3166,  2.7838],
        [-2.3766,  2.7024],
        [-2.3957,  2.7707],
        [-2.4582,  2.7383],
        [-2.2910,  2.7872],
        [-2.4677,  2.7270],
        [-2.3830,  2.7325]])
haribol tensor([[-2.3239,  2.7227],
        [-2.1862,  2.6903],
        [-2.4243,  2.7633],
        [-2.4203,  2.7634],
        [-2.3226,  2.7706],
        [-2.4257,  2.7616],
        [-2.3293,  2.7742],
        [-2.4345,  2.7699]])
haribol tensor([[-2.4814,  2.7733],
        [-2.3944,  2.8230],
        [-2.3007,  2.7594],
        [-2.4473,  2.7477],
        [-2.3757,  2.7658],
        [-2.3945,  2.7619],
        [-2.3323,  2.7983],
        [-2.3333,  2.8055]])
haribol tensor([[-2.3625,  2.6430],
        [-2.2851,  2.7492],
        [-2.3326,  2.7635],
        [-2.4081,  2.7717],
        [-2.4304,  2.7277],
        [-2.4526,  2.7470],
        [-2.4405,  2.7864],
        [-2.4881,  2.7872]])
haribol tensor([[-2.3435,  2.7458],
        [-2.2802,  2.7571],
        [-2.3533,  2.7689],
        [-2.3546,  2.7799],
        [-2.3660,  2.6568],
        [-2.4524,  2.7607],
        [-2.4026,  2.7772],
        [-2.3471,  2.6968]])
Training accuracy : 46.25%

In [52]:
def calc_loss_batch(input_batch, target_batch, model, device):
    input_batch = input_batch.to(device)
    target_batch= target_batch.to(device)
    logits= model(input_batch)[:, -1, :]
    loss= torch.nn.functional.cross_entropy(logits, target_batch)
    return loss

In [56]:
def calc_loss_loader(data_loader, model, device, num_batches= None):
    total_loss=0
    if len(data_loader)==0:
        return float("nan")
    
    elif num_batches is None:
        num_batches = len(data_loader)
    else:
        num_batches= min(num_batches, len(data_loader))
    
    for i , (input_batch, target_batch ) in enumerate(data_loader):
        if i< num_batches:
            loss= calc_loss_batch(
                input_batch, target_batch,model, device
            )
            total_loss += loss.item()

        else:
            break
    
    return total_loss / num_batches

In [ ]:
# lets find the initial loss of each dataset
with torch.no_grad():
    train_loss= calc_loss_loader(
        train_loader, model, device, num_batches=5
    )
    print("train loss", train_loss)  #yes yes you can find for validation and test also\

train loss 2.325549602508545

In [62]:
def train_classifier_simple(
        model, train_loader, val_loader, optimizer, device,
        num_epochs, eval_freq, eval_iter):
    train_losses, val_losses, train_accs, val_accs = [], [], [], []   #1
    examples_seen, global_step = 0, -1

    for epoch in range(num_epochs):   #2
        model.train()                 #3

        for input_batch, target_batch in train_loader:
            optimizer.zero_grad()     #4

            loss = calc_loss_batch(
                input_batch, target_batch, model, device
            )

            loss.backward()           #5
            optimizer.step()          #6
            examples_seen += input_batch.shape[0]   #7
            global_step += 1

            if global_step % eval_freq == 0:        #8
                train_loss, val_loss = evaluate_model(
                    model, train_loader, val_loader, device, eval_iter
                )
                train_losses.append(train_loss)
                val_losses.append(val_loss)

                print(
                    f"Ep {epoch+1} (Step {global_step:06d}): "
                    f"Train loss {train_loss:.3f}, "
                    f"Val loss {val_loss:.3f}"
                )

        train_accuracy = calc_accuracy_loader(      #9
            train_loader, model, device, num_batches=eval_iter
        )

        val_accuracy = calc_accuracy_loader(
            val_loader, model, device, num_batches=eval_iter
        )

        print(f"Training accuracy: {train_accuracy*100:.2f}% | ", end="")
        print(f"Validation accuracy: {val_accuracy*100:.2f}%")

        train_accs.append(train_accuracy)
        val_accs.append(val_accuracy)

    return train_losses, val_losses, train_accs, val_accs, examples_seen

In [60]:
def evaluate_model(model, train_loader, val_loader, device, eval_iter):
    model.eval()
    with torch.no_grad():
        train_loss= calc_loss_loader(
            train_loader, model, device, num_batches= eval_iter
        )
        val_loss= calc_loss_loader(
            val_loader, model, device, num_batches= eval_iter
        )

    model.train()
    return train_loss, val_loss

In [63]:
import time
start_time= time.time()
torch.manual_seed(123)
optimizer= torch.optim.AdamW(model.parameters(), lr= 5e-5, weight_decay= 0.1)
num_epochs=5

train_losses, val_losses, train_accs, val_accs, examples_seen= \
    train_classifier_simple(
        model, train_loader, val_loader, optimizer, device,
        num_epochs= num_epochs, eval_freq=50,
        eval_iter=5
    )

end_time= time.time()
execution_time_minutes= (end_time - start_time)/60
print(f"training complete in {execution_time_minutes}")

Ep 1 (Step 000000): Train loss 2.153, Val loss 2.392
Ep 1 (Step 000050): Train loss 0.617, Val loss 0.637
Ep 1 (Step 000100): Train loss 0.523, Val loss 0.557
haribol tensor([[ 0.6315,  0.4142],
        [ 0.4163,  0.6638],
        [ 0.9974,  0.1842],
        [ 0.4806,  0.6430],
        [ 0.7462,  0.4111],
        [ 0.9333,  0.2625],
        [ 1.2382, -0.1150],
        [ 0.6085,  0.5267]])
haribol tensor([[ 0.5686,  0.5293],
        [ 1.8539, -0.5943],
        [ 0.3747,  0.7147],
        [ 0.6276,  0.5102],
        [ 1.5586, -0.3700],
        [ 0.6046,  0.5496],
        [ 0.6486,  0.4687],
        [ 1.3622, -0.2048]])
haribol tensor([[ 0.4665,  0.6443],
        [ 1.3769, -0.1646],
        [ 0.8416,  0.2516],
        [ 1.4001, -0.2192],
        [-0.0355,  0.9099],
        [ 1.1614, -0.0410],
        [ 0.4793,  0.5676],
        [ 1.4890, -0.3049]])
haribol tensor([[ 0.6105,  0.5106],
        [ 0.6274,  0.5126],
        [ 0.4669,  0.6398],
        [ 1.3899, -0.1978],
        [ 0.4415,  0.7201],
        [ 1.3354, -0.1660],
        [ 1.0595,  0.1010],
        [ 1.2880, -0.1486]])
haribol tensor([[ 0.4252,  0.6699],
        [ 0.6074,  0.5329],
        [ 1.0688,  0.0498],
        [ 1.7683, -0.4768],
        [ 0.5252,  0.5698],
        [ 1.5236, -0.3555],
        [ 0.5759,  0.5341],
        [ 1.1149,  0.0396]])
haribol tensor([[ 0.4493,  0.6937],
        [ 0.7262,  0.3856],
        [ 1.1831, -0.0158],
        [ 1.4211, -0.2490],
        [ 0.6193,  0.5273],
        [ 0.9176,  0.2251],
        [ 0.4462,  0.6416],
        [ 1.6997, -0.4647]])
haribol tensor([[ 0.4348,  0.6650],
        [ 1.1061,  0.0725],
        [ 0.8762,  0.2760],
        [ 0.5352,  0.6094],
        [ 1.6214, -0.3392],
        [ 0.4706,  0.6053],
        [ 1.5280, -0.3317],
        [ 0.6708,  0.4506]])
haribol tensor([[ 1.1147,  0.0187],
        [ 0.7190,  0.4494],
        [ 0.6501,  0.4307],
        [ 0.8827,  0.2376],
        [ 0.7169,  0.3705],
        [ 1.9560, -0.6034],
        [ 0.8469,  0.3253],
        [ 0.6496,  0.4720]])
haribol tensor([[ 1.6703, -0.4196],
        [ 0.7180,  0.3946],
        [ 0.3814,  0.7611],
        [ 0.4371,  0.6008],
        [ 0.5489,  0.5953],
        [ 0.4219,  0.6404],
        [ 0.7241,  0.3723],
        [ 0.6825,  0.5724]])
haribol tensor([[ 1.1495,  0.0029],
        [ 1.3315, -0.1364],
        [ 0.6852,  0.3965],
        [ 0.2629,  0.7675],
        [ 1.2394, -0.0687],
        [ 0.6235,  0.4307],
        [ 0.4304,  0.7160],
        [ 1.1257,  0.0437]])
Training accuracy: 70.00% | Validation accuracy: 72.50%
Ep 2 (Step 000150): Train loss 0.561, Val loss 0.489
Ep 2 (Step 000200): Train loss 0.419, Val loss 0.397
Ep 2 (Step 000250): Train loss 0.409, Val loss 0.353
haribol tensor([[ 0.4691,  0.6908],
        [ 1.6551, -0.3138],
        [ 1.5392, -0.1884],
        [ 1.1208,  0.1316],
        [-0.6788,  1.6798],
        [ 0.5196,  0.6547],
        [ 1.0711,  0.1352],
        [ 1.5018, -0.2128]])
haribol tensor([[-0.1691,  1.3824],
        [ 0.3301,  0.8849],
        [-0.2776,  1.3826],
        [ 1.2999,  0.0377],
        [-0.3512,  1.4030],
        [-0.5017,  1.6041],
        [-0.2320,  1.2780],
        [-0.0501,  1.1237]])
haribol tensor([[ 2.1308, -0.7634],
        [ 0.9887,  0.2640],
        [ 1.1024,  0.1128],
        [-0.8966,  1.9367],
        [-0.6063,  1.6895],
        [ 1.5988, -0.2548],
        [-0.4233,  1.5364],
        [-0.8696,  1.9008]])
haribol tensor([[-0.7606,  1.7697],
        [-0.4573,  1.5141],
        [ 1.3452, -0.0498],
        [ 1.3059,  0.0026],
        [ 1.4968, -0.2215],
        [ 0.1782,  0.9558],
        [ 1.1581,  0.1795],
        [-0.1554,  1.2352]])
haribol tensor([[ 2.7702, -1.2532],
        [ 2.6058, -1.0754],
        [ 0.3140,  0.8250],
        [-0.0428,  1.1625],
        [ 2.1980, -0.8056],
        [ 0.2390,  0.9306],
        [-0.0311,  1.1373],
        [ 1.1929,  0.0911]])
haribol tensor([[-0.7767,  1.8568],
        [ 0.0755,  1.0477],
        [ 1.2746,  0.0198],
        [ 1.7549, -0.4371],
        [-0.2698,  1.4000],
        [ 0.5509,  0.6500],
        [-0.4828,  1.5401],
        [ 2.3441, -0.9162]])
haribol tensor([[-0.5262,  1.6029],
        [ 1.1442,  0.1595],
        [ 0.4855,  0.7157],
        [-0.6945,  1.7750],
        [ 2.2534, -0.7699],
        [-0.6023,  1.6256],
        [ 2.0350, -0.6572],
        [-0.2807,  1.3629]])
haribol tensor([[ 1.2703, -0.0195],
        [ 0.0937,  1.0947],
        [-0.0881,  1.1724],
        [ 0.6442,  0.5435],
        [ 0.0879,  1.0139],
        [ 3.1414, -1.5015],
        [ 0.3083,  0.8936],
        [-0.1452,  1.2576]])
haribol tensor([[ 2.3358, -0.8747],
        [ 0.0931,  1.0300],
        [-0.9156,  1.9821],
        [-0.5451,  1.5608],
        [-0.4253,  1.5332],
        [-0.5660,  1.5883],
        [ 0.0900,  1.0189],
        [-0.4300,  1.6351]])
haribol tensor([[ 1.2595,  0.0166],
        [ 1.7205, -0.3648],
        [ 0.2340,  0.8881],
        [-0.8989,  1.8716],
        [ 1.4600, -0.1443],
        [-0.0131,  1.0773],
        [-0.6576,  1.7560],
        [ 1.1816,  0.0869]])
Training accuracy: 82.50% | Validation accuracy: 85.00%
Ep 3 (Step 000300): Train loss 0.333, Val loss 0.320
Ep 3 (Step 000350): Train loss 0.340, Val loss 0.306
haribol tensor([[-1.1610,  2.1155],
        [-0.4040,  1.4551],
        [ 2.7582, -1.4217],
        [-1.1097,  2.2843],
        [-0.0437,  1.2056],
        [-0.8298,  1.7750],
        [ 2.5558, -1.2706],
        [-1.1084,  2.2679]])
haribol tensor([[ 0.6856,  0.3621],
        [ 0.1237,  0.9429],
        [ 1.2294, -0.1235],
        [-0.8534,  1.9880],
        [ 2.8155, -1.4969],
        [ 0.0278,  1.1350],
        [-0.7414,  2.0406],
        [-0.9421,  2.0486]])
haribol tensor([[-0.9451,  2.0863],
        [-0.5281,  1.5930],
        [-1.0471,  2.1068],
        [-0.9829,  1.6661],
        [-1.1393,  2.2286],
        [-0.7736,  1.7470],
        [ 0.5719,  0.4618],
        [-1.0541,  2.0746]])
haribol tensor([[ 1.2457, -0.0965],
        [-1.2192,  2.2974],
        [ 1.2072, -0.1155],
        [ 2.4198, -1.2094],
        [-1.3377,  2.5495],
        [-1.1838,  2.1910],
        [-1.3760,  2.4019],
        [-1.0372,  2.1821]])
haribol tensor([[-0.4294,  1.4563],
        [ 0.2601,  0.7928],
        [-1.1768,  2.2428],
        [ 2.7520, -1.4631],
        [ 1.0740,  0.0611],
        [-0.9364,  2.0315],
        [ 1.9868, -0.7871],
        [ 2.4736, -1.2271]])
haribol tensor([[-1.1578,  2.3719],
        [-0.5088,  1.6900],
        [ 1.4717, -0.2656],
        [ 2.0331, -0.8533],
        [-0.9672,  2.0857],
        [ 0.6997,  0.4013],
        [-1.0834,  2.1695],
        [ 2.7142, -1.4144]])
haribol tensor([[-1.1081,  2.2289],
        [ 1.3344, -0.1429],
        [ 0.6275,  0.4706],
        [-1.0920,  2.1754],
        [ 2.5431, -1.1523],
        [-1.1272,  2.1004],
        [ 2.3633, -1.1240],
        [-0.2883,  1.3663]])
haribol tensor([[ 1.5322, -0.3588],
        [ 0.1279,  0.9717],
        [-0.0425,  1.0405],
        [ 0.7980,  0.2856],
        [ 0.0623,  1.1172],
        [ 3.5679, -2.0353],
        [-0.3324,  1.4925],
        [-0.7185,  1.9058]])
haribol tensor([[ 2.7131, -1.3395],
        [-0.4533,  1.5390],
        [-1.1635,  2.2970],
        [-0.7799,  1.9273],
        [-0.9296,  2.0353],
        [-0.5481,  1.5392],
        [-0.1790,  1.3717],
        [-0.9451,  2.0863]])
haribol tensor([[ 1.5300, -0.3608],
        [ 2.0291, -0.7613],
        [ 0.4368,  0.6562],
        [-1.1286,  2.2112],
        [ 1.7195, -0.5159],
        [ 0.0931,  0.8755],
        [-0.9452,  2.0652],
        [ 1.4361, -0.2759]])
Training accuracy: 90.00% | Validation accuracy: 90.00%
Ep 4 (Step 000400): Train loss 0.136, Val loss 0.200
Ep 4 (Step 000450): Train loss 0.153, Val loss 0.132
Ep 4 (Step 000500): Train loss 0.222, Val loss 0.137
haribol tensor([[ 2.0541, -0.7883],
        [-1.9995,  3.2990],
        [ 0.3769,  0.9238],
        [-1.8402,  3.2452],
        [-2.3842,  3.5165],
        [ 1.0265,  0.4369],
        [-2.4386,  3.6165],
        [ 3.6127, -2.3735]])
haribol tensor([[-0.4700,  1.5018],
        [-2.3012,  3.7272],
        [ 2.3525, -1.0985],
        [ 1.4268, -0.1936],
        [ 3.8186, -2.6016],
        [-1.6766,  3.0693],
        [-1.5342,  2.7776],
        [-1.8130,  3.2018]])
haribol tensor([[ 3.1674, -1.9075],
        [-1.5875,  2.7108],
        [ 2.6478, -1.5207],
        [ 3.2235, -1.9194],
        [-2.0698,  3.4122],
        [-1.7104,  3.1287],
        [ 3.2020, -1.9090],
        [ 2.4364, -1.2425]])
haribol tensor([[ 2.3912, -1.2059],
        [-2.0952,  3.2690],
        [-2.1171,  3.2183],
        [-0.2368,  1.4227],
        [-1.9540,  3.2878],
        [ 1.0435,  0.1783],
        [ 2.2113, -0.8303],
        [ 2.6669, -1.2542]])
haribol tensor([[-0.5722,  1.7986],
        [ 2.2601, -0.8485],
        [ 2.1385, -0.8946],
        [ 0.4450,  0.8342],
        [ 1.2655, -0.1328],
        [ 3.2239, -1.8304],
        [-1.6087,  2.8992],
        [ 1.5049, -0.2218]])
haribol tensor([[-2.1196,  3.4796],
        [-1.8011,  3.1265],
        [ 2.0051, -0.7614],
        [ 2.5573, -1.3713],
        [-2.2963,  3.6254],
        [ 1.3137, -0.1788],
        [-2.2092,  3.4909],
        [ 3.6290, -2.2218]])
haribol tensor([[-2.2599,  3.5191],
        [ 1.9002, -0.7086],
        [ 1.2150, -0.0846],
        [-2.2058,  3.4235],
        [ 2.8915, -1.4713],
        [-2.3685,  3.5330],
        [ 2.9652, -1.7765],
        [-0.3928,  1.7378]])
haribol tensor([[ 2.0360, -0.7863],
        [-0.0063,  1.2329],
        [ 0.5527,  0.4702],
        [ 1.1870, -0.0188],
        [-0.5491,  1.9097],
        [ 4.0819, -2.5942],
        [-1.7899,  3.1141],
        [-1.9177,  3.2745]])
haribol tensor([[ 3.3043, -1.6648],
        [-1.7997,  3.0036],
        [-2.0288,  3.3424],
        [-1.5303,  2.8252],
        [-2.1634,  3.4581],
        [-0.3681,  1.5069],
        [-1.4712,  2.9386],
        [-2.4046,  3.6888]])
haribol tensor([[ 2.4737, -1.1841],
        [ 2.7714, -1.3430],
        [ 1.0879,  0.1543],
        [-1.7930,  3.0206],
        [ 2.2740, -1.0685],
        [ 0.6869,  0.3417],
        [-2.0329,  3.3629],
        [ 2.0824, -0.8847]])
Training accuracy: 100.00% | Validation accuracy: 97.50%
Ep 5 (Step 000550): Train loss 0.207, Val loss 0.143
Ep 5 (Step 000600): Train loss 0.083, Val loss 0.074
haribol tensor([[ 3.5760, -2.3861],
        [-2.3365,  3.6365],
        [ 2.4885, -1.2492],
        [-2.8862,  4.1828],
        [-0.7035,  1.9122],
        [-2.5527,  3.7141],
        [ 3.3480, -2.1997],
        [ 2.5631, -1.4891]])
haribol tensor([[-2.5422,  3.8798],
        [-2.0787,  3.4894],
        [ 3.1689, -2.0313],
        [ 1.3624, -0.2466],
        [ 3.2578, -2.0704],
        [ 1.6947, -0.5600],
        [ 3.4266, -1.9475],
        [ 3.1237, -1.9125]])
haribol tensor([[ 2.3315, -1.0705],
        [-1.6734,  3.0237],
        [-2.2829,  3.5746],
        [-1.2496,  2.7248],
        [ 2.6708, -1.6151],
        [ 3.6890, -2.5521],
        [ 3.4051, -2.2808],
        [-2.5415,  3.8534]])
haribol tensor([[ 2.4856, -1.3450],
        [-0.8097,  1.9592],
        [-0.6022,  1.8938],
        [ 3.1957, -2.0227],
        [-1.9454,  3.3520],
        [ 2.3495, -1.1046],
        [ 3.1597, -1.9960],
        [-2.2199,  3.5637]])
haribol tensor([[-2.6239,  3.9370],
        [-2.5205,  3.8803],
        [-2.2236,  3.5084],
        [ 3.6493, -2.4086],
        [ 3.3300, -2.2509],
        [-1.7640,  3.1857],
        [ 2.7796, -1.6359],
        [-0.7239,  1.9635]])
haribol tensor([[-2.3731,  3.7528],
        [-2.1764,  3.5279],
        [ 2.4470, -1.3107],
        [ 2.6722, -1.5463],
        [-2.6298,  4.0101],
        [ 1.8704, -0.8423],
        [-2.5467,  3.8812],
        [ 4.2195, -2.8799]])
haribol tensor([[-2.6143,  3.8898],
        [ 2.4087, -1.3480],
        [ 1.6867, -0.6398],
        [-2.5080,  3.7526],
        [ 3.1415, -1.8310],
        [-2.7295,  3.9556],
        [ 3.3543, -2.2884],
        [-0.2228,  1.5712]])
haribol tensor([[ 2.4315, -1.2744],
        [-0.1364,  1.3598],
        [ 1.2159, -0.3286],
        [ 1.3886, -0.2499],
        [-0.7497,  2.0869],
        [ 4.2528, -2.8877],
        [-2.1986,  3.5611],
        [-2.2427,  3.6319]])
haribol tensor([[ 3.6962, -2.1090],
        [-2.1967,  3.4314],
        [-2.2612,  3.6103],
        [-1.4133,  2.6685],
        [-2.4808,  3.8262],
        [-0.2259,  1.3426],
        [-1.8806,  3.4200],
        [-2.8571,  4.2008]])
haribol tensor([[ 3.1273, -1.9072],
        [ 3.3657, -1.9552],
        [ 1.5524, -0.3620],
        [-1.9485,  3.1896],
        [ 2.6078, -1.5098],
        [ 1.2518, -0.3214],
        [-2.2699,  3.6314],
        [ 2.3750, -1.1706]])
Training accuracy: 100.00% | Validation accuracy: 97.50%
training complete in 22.930210185050964

In [64]:
torch.save(model.state_dict(), "review_classifier.pth")

In [ ]:
# print(model.tok_emb)

Embedding(50257, 768)

In [72]:
# print(model)

In [ ]:
def classify_review(
    text, model, tokenizer, device, max_length=None,
    pad_token_id= 50256):
    model.eval()

    input_ids= tokenizer.encode(text)
    supported_context_length= model.pos_emb.weight.shape[1]
    
    input_ids= input_ids[:min(
        max_length, supported_context_length
    )]
    input_ids+= [pad_token_id] *(max_length - len(input_ids))

    input_tensor

In [73]:
s= [1,2,3]

In [74]:
s = s+ ["hari"]
s

[1, 2, 3, 'hari']